<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>Пічалька. Такого запиту немає :(</h1>
                <h2>404 Not Found</h2>
                <div class="error-details">
                    Спробуйте може шось типо /sprint/{sprint_id} або /wokrload/{month_id}/{year}
                </div>

            </div>
        </div>
    </div>
</div>